version: '3'

services:

  broker-service:
    build:
      context: broker-service
      dockerfile: broker-service.dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1